services:
  api:
    image: meli-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "10000:10000"

  web:
    image: meli-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
